### ISSUE TITLE
Add a flake app for running our neovim config

### ISSUE THREAD

**Issue by srid** [juspay/nix-dev-home#16]
`nix run github:juspay/nix-dev-home#neovim` should run neovim with the config in this repo, without depending on any of user's dotfiles or local $HOME cache.

cf. https://old.reddit.com/r/NixOS/comments/1aulb75/easy_neovim_with_configuration_and_runnable_with/

**Comment by shivaraj-bh** [comment]
Mic92 has a runnable nvim config: https://github.com/Mic92/dotfiles?tab=readme-ov-file#use-my-nvim-configuration-as-a-standalone-without-installing-dotfiles

**Comment by srid** [comment]
It's not generic enough.

https://github.com/Mic92/dotfiles/blob/b2ff14454465c10d00c4239eea0785583ddf9a35/home-manager/modules/neovim/nvim-standalone.nix#L3-L30

We want something that works with our nixvim configuration.

**Comment by srid** [comment]
https://github.com/niksingh710/nvix?tab=readme-ov-file#quick-run

**Comment by niksingh710** [comment]
@srid 

I have fixed this in [2 commits](https://github.com/juspay/nix-dev-home/compare/main...niksingh710:nix-dev-home:main).

Check them out, and if everything seems fine, then I will create an MR.

```sh
nix run github:niksingh710/nix-dev-home#neovim
```

- Switched nixvim config from [`home -> standalone`](https://nix-community.github.io/nixvim/modules/standalone.html)
- Moved the `neovim.nix` config to `pkgs` dir. Representing package set.
- Added the same package in `home/packages.nix` to make sure that when home is built, then package is there.
