### ISSUE TITLE
should factoring, imports, and directory tree mirror `srid/nixos-config`?

### ISSUE THREAD

**Issue by cameronraysmith** [juspay/nix-dev-home#5]
I realize if this is home-manager only and forever it wouldn't matter much, but it might be helpful if the factoring were a bit more in line with [srid/nixos-config](https://github.com/srid/nixos-config) to support comprehension of the abstraction that arises with multiple systems, beyond home-manager, etc.

An [example of this](https://github.com/cameronraysmith/nixpod-home/tree/f0692b88d9db1bf7d5ea0944093c6f356005112d) leads to a directory tree like

```
.
├── .envrc
├── .github
│   └── workflows
├── .gitignore
├── flake.lock
├── flake.nix
├── home
│   ├── default.nix
│   ├── neovim
│   ├── starship.nix
│   └── terminal.nix
└──justfile
```

but, more importantly, I find the contents of flake.nix, default.nix + terminal.nix (vs home.nix), etc to be more legible. 

I'd be happy to submit those changes in reasonable chunks or feel free to consider doing so in future updates since it is essentially just turning the dial slightly further in the direction of srid/nixos-config. No worries if this is undesirable for some reason I haven't accounted for.

Many thanks for `nix-dev-home` among other things!

**Comment by srid** [comment]
That sounds like a good idea. Yes, PR would be very welcome, @cameronraysmith 

You can also add a `justfile` (we're using it increasingly in other repos).
