### ISSUE TITLE
>20mins to activate on fresh install

### ISSUE THREAD

**Issue by srid** [juspay/nix-dev-home#61]
From @shivaraj-bh 

<img width="552" alt="image" src="https://github.com/user-attachments/assets/f101ab93-cf1d-4b1a-a512-7e28cea7968a">

**Comment by srid** [comment]
@shivaraj-bh I wonder if this is because of 03d764e142ed046e6f8eb2b6d0eff0f2b8fa49d7

I figured that the use of static binary should download only minimal closures, but it looks like it is doing more than that. 

We can wait for https://github.com/juspay/omnix/issues/204 - or lets comment out omnix if it is too much trouble in the meanwhile.

**Comment by shivaraj-bh** [comment]
> @shivaraj-bh I wonder if this is because of [03d764e](https://github.com/juspay/nix-dev-home/commit/03d764e142ed046e6f8eb2b6d0eff0f2b8fa49d7)
> 
> I figured that the use of static binary should download only minimal closures, but it looks like it is doing more than that.
> 


That would be true if we had a cache for it, but that’s not the case initialising `nix-dev-home`

**Comment by shivaraj-bh** [comment]
> We can wait for https://github.com/juspay/omnix/issues/204 - or lets comment out omnix if it is too much trouble in the meanwhile.

https://github.com/juspay/nix-dev-home/pull/62
