### ISSUE TITLE
Lots of `warning: unknown setting`

### ISSUE THREAD

**Issue by srid** [juspay/nix-dev-home#77]
Getting this on fresh setup of WSL Ubuntu:

![image](https://github.com/user-attachments/assets/8549f3c4-409e-4394-abfe-e034559063b5)

**Comment by srid** [comment]
This diffs gets rid of the warning, but we need a proper fix:

```diff
diff --git a/nix/modules/home/nix.nix b/nix/modules/home/nix.nix
index cea794e..cf83aac 100644
--- a/nix/modules/home/nix.nix
+++ b/nix/modules/home/nix.nix
@@ -4,7 +4,7 @@
   nix = {
     # Which Nix version to use
     # https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=nix
-    package = pkgs.nix;
+    package = pkgs.nixVersions.nix_2_23;
 
     registry.nixpkgs.flake = flake.inputs.nixpkgs; # https://yusef.napora.org/blog/pinning-nixpkgs-flake/
 
```

**Comment by srid** [comment]
Aside: https://github.com/DeterminateSystems/nix-installer/issues/1165

**Comment by niksingh710** [comment]
Ig having an overlay for stable pkgs should be fine?

e.g

https://github.com/niksingh710/ndots/blob/19757f8b37013323b2cc681b4e46ebce5fef44c3/nixos/core/overlays/default.nix#L2C1-L10C1

After this overlay refering a stable package would be like `pkgs.stable.nix`

I keep two nixpkgs inputs `nixpkgs=unstable` `nixpkgs-stable=The latest stable`

**Comment by srid** [comment]
I think we should just switch to stable nixpkgs by default. Does that fix this issue?

**Comment by niksingh710** [comment]
Yes, Switching to stable should resolve it.
But adding an overlay will allow us to have the best of both `unstable` and `stable`.

Unable to perform the test rn.
Have to enable wsl in virtual windows.

My solution is based on the diff you provided as it uses specific version of `nix` package.

**Comment by srid** [comment]
4a40dee541322bb74d4db8a5b9685bf89e9df605 + 9d4a4170ed2f1329cb985f31ec66756190d94aa5 may fix this.

**Comment by srid** [comment]
Actually not. 

The issue is that DetSys installer creates `/etc/nix/nix.conf` using options from latest Nix, but we are trying to use stable Nix in home-manager. And home-manager can only create `nix.conf` in $HOME; it can't manage the global one, unless we switch to nix-darwin.

**Comment by srid** [comment]
> Yes, Switching to stable should resolve it.

Have you tried this with DetSys installer?

**Comment by srid** [comment]
b65f5b459d1bb9c2db9d8604c516e5293b5c581d should fix this, at least when using DetSys installer.

**Comment by niksingh710** [comment]
> > Yes, Switching to stable should resolve it.
> 
> Have you tried this with DetSys installer?

nop, I believe the issue is due to a mismatch in Nix versions.

**Comment by srid** [comment]
af55a164bb75692e75c90878d9030af736e1ed82

If this warning pops up again, let's re-open this issue and then diagnose and fix it properly.
