### ISSUE TITLE
Video demo in README.md is outdated

### ISSUE THREAD

**Issue by rsrohitsingh682** [juspay/nix-dev-home#80]
https://github.com/juspay/nix-dev-home/blob/7614020d01442882cca7f58ae264b6384b1b70d5/README.md?plain=1#L43

**Comment by srid** [comment]
Let's remove the demo, since it is getting more automated (#11) anyway, to the point of one-click install. https://github.com/juspay/omnix/issues/207#issuecomment-2364722319
